### ISSUE TITLE
Support mongodb `v5`

### ISSUE THREAD

**Issue by razorness** [veliovgroup/josk#13]
Current version of Josk and so mail-time does not support `mongodb` `v5` and higher. [Callbacks for `findBy` are not supported anymore](https://github.com/mongodb/node-mongodb-native/releases/tag/v5.0.0).

**Comment by dr-dimitru** [comment]
@razorness thank you for bringing this to my attention. [`v3.1.0`](https://github.com/veliovgroup/josk/releases/tag/3.1.0) support all active branches of MongoDB and Node.js

Feel free to reopen it in case if the issue is still persists on your end.
